version: '3.8'

services:
  web:
    build: ./app
    # # command: python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000
    # # command: python manage.py createsuperuser && gunicorn my.wsgi:application --settings=my.settings.conf
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn docker_django.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      # - static_volume:/usr/src/app/static/
    # ports:
    #   - 8000:8080
    expose:
      - 8080
    env_file:
      - ./.env.dev
    # environment:
    #   - DJANGO_SUPERUSER_USERNAME=docker_django
    #   - DJANGO_SUPERUSER_EMAIL=docker_django@example.com
    #   - DJANGO_SUPERUSER_PASSWORD=docker_django_dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - static_volume:/home/app/web/staticfiles
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker_django
      - POSTGRES_PASSWORD=docker_django
      - POSTGRES_DB=docker_django_dev
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: