version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn docker_django.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8080
    env_file:
      - ./.env.dev
    environment:
      - NEWDB=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=secret
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker_django
      - POSTGRES_PASSWORD=docker_django
      - POSTGRES_DB=docker_django_dev
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
